// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-zE4hevN4_U8QxpbMMwDJpG1vnkaAqws',
    appId: '1:916513331598:web:5f0fcd76be88fe6d082cdf',
    messagingSenderId: '916513331598',
    projectId: 'lunova-474e2',
    authDomain: 'lunova-474e2.firebaseapp.com',
    storageBucket: 'lunova-474e2.firebasestorage.app',
    measurementId: 'G-DYWB70PWQJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7ONqTBLOHfVsfJ6eU2VeRQYJb97WXrg0',
    appId: '1:916513331598:android:a11f2668204ea4f5082cdf',
    messagingSenderId: '916513331598',
    projectId: 'lunova-474e2',
    storageBucket: 'lunova-474e2.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-zE4hevN4_U8QxpbMMwDJpG1vnkaAqws',
    appId: '1:916513331598:web:4f6a2f117ddf4f88082cdf',
    messagingSenderId: '916513331598',
    projectId: 'lunova-474e2',
    authDomain: 'lunova-474e2.firebaseapp.com',
    storageBucket: 'lunova-474e2.firebasestorage.app',
    measurementId: 'G-NLJ84DWN3K',
  );

}